# Generated by Django 4.2 on 2023-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjivocabulary',
            name='kana',
        ),
        migrations.AddField(
            model_name='kanjivocabulary',
            name='kunyomi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kanjivocabulary',
            name='onyomi',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
